steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/build:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './build-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/build',
      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/build:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/build',
      'steamwheedle-cartel/run-workload/build'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/runtime:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './runtime-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/runtime',
      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/runtime:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/runtime'
    ]
images: [
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/build:latest',
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-workload/runtime:latest'
]
